eCommunity update
conda/conda-dot-org pull request #197
Opened 2024-08-08 09:31 UTC by wolfv

### Description

- [ ] If I have added a new page to `learn/` or `community/`, I have added it to the corresponding `_sidebar.json` file.

2024-08-08 10:20 UTC, jezdez requested changes
Thanks for openning the PR, the video is presented as a conda community update but it's discussing conda-forge and pixi, neither of which are conda community projects.

This wasn't discussed with the conda communications team before as a new inititive. So I have to say I'm a little flummoxed about it, it's not as if I haven't been trying to faciliate the participation of @wolfv and his company, why presenting this as a done deal?

@wolfv Was this the topic you brought up recently when you asked to "record a podcast" with me?

A few things that I think need to happen before we merge and publish it:

- the prefix.dev GmbH heavy theming throws me off, just like having it hosted on a company youtube channel. This is fixable by setting up a youtube channel and upload the video there.
- pixi is as you are well aware _not_ a conda community project, but a commercial project by @wolfv's company, which makes this framing as a conda community update a little unsavory in my book. This is after all the type of vendor focus that the conda governance policy was set up to prevent, and that I've personally tried very hard for us to walk away from.
- Neither @wolfv nor @ocefpaf are members of the conda communications team and it hadn't been brought up with the conda steering council before recording it, so I'd be interested to hear more about the plans for this community update (E.g. how often? What is the focus? How does this relate to the conda community sync meeting? Who will be the target audience?)

2024-08-08 10:46 UTC, wolfv commented
Yes, I had this format in mind when I talked to you about a Podcast (but more with the NumFOCUS transition in mind and the revamping of the whole conda-community effort).

I think both conda-forge and pixi are very interesting topics to the conda community. Not sure why we wouldn't want to hear about them :) Just as we would want to hear from Docker, Nix or Homebrew.

I think most people will remember more "conda" than "prefix". We are not selling "pixi" so it's not really fair to classify it as a "commercial product".

We are hoping to do this kind of recordings roughly once or twice a month. Probably more once a month. Topics should be anything touching the conda community:

- Talking about mamba with @SylvainCorlay
- Talking about conda recipe manager e.g. with Schuyler
- Talking about rez & conda with e.g. with JC
- conda-forge infrastructure and bots e.g. with Matt Becker

... and more ideas along those lines (no one knows about these ideas yet, so just putting them out here for now).

If you want we can come up with a different name of course. It would sadden me (because I am hoping to reinvigorate the community) but it's no problem!

2024-08-08 10:56 UTC, wolfv commented
Some ideas for alternative names:

- "Conda Convo"
- "All things Conda"
- "Package Party"

Would one of those alleviate your concerns @jezdez?

2024-08-08 16:29 UTC, dashagurova commented
@wolfv I love the idea of podcast/chats for the conda ecosystem! If the goal is to reinvigorate the conda community, I think that starting a dedicated conda ecosystem YouTube channel would make more sense. We could host the videos there and then share them through the official conda website and social media channels. And I would be happy to volunteer to help and collaborate on this! I’ve had a similar idea of starting conda community podcast/chats someday, where we talk about/with the projects from the conda ecosystem, including pixi, mamba, conda, conda-forge (many more from conda and conda incubator) and related or interesting topics (like packaging in general).

2024-08-08 18:08 UTC, wolfv commented
@dashagurova - great! If you make the channel I can move the video there. Maybe you can give me content creator rights on that channel?

I wouldn't mind having other hosts on this "show", either :)

2024-08-09 18:52 UTC, jezdez commented
Hey @wolfv, sorry for the slow reply, I like the idea of doing more outreach for the amazing things that happen in our ecosystem, despite my worries above, my main focus remains the sustainability of the community and starting a whole new project without plan sounds like we'd be setting us up for failure. Thanks for chiming in @dashagurova as well!

Could we start putting together a plan in the conda/communications repo ([as an issue](https://github.com/conda/communications/issues?q=sort%3Aupdated-desc+is%3Aissue+is%3Aopen)?) with a publication schedule, roles and purposes, so that we can meaningfully say this comes from the community? (that's why we set up the communications team originally after all) I'm a little uncertain how else to make sure this doesn't end up being a project that fizzles out after a short while. I do appreciate your willingness do the work @wolfv, maybe I could encourage you to participate?

Regarding naming, it really depends on the format, is this mostly going to be 1:1 converstaions like fireside chats? Would we consider a panel or hosted talks?

2024-08-22 15:31 UTC, dashagurova commented on blog/2024-08-21-chatting-with-the-conda-community.mdx
> +tags: [announcement, conda-community-update]
```suggestion
tags: [announcement]
```

2024-08-22 15:33 UTC, dashagurova commented on blog/news.json
> +      "conda-community-update"
```suggestion
      "announcement"
```

2024-08-27 16:20 UTC, jezdez reviewed
Thanks for updating @wolfv!

2024-09-02 12:22 UTC, wolfv commented
I updated the date. IMO we can merge this one if people are fine with it

2024-09-11 22:22 UTC, wolfv commented on blog/2024-09-02-chatting-with-the-conda-community.mdx
> +tags: [announcement]
Done!

2024-09-11 22:22 UTC, wolfv commented on static/img/blog/2024-08-21-chatting-with-conda-community/banner.png
I moved it to a differnet folder.

2024-09-11 22:22 UTC, wolfv commented
I'll merge this tomorrow if no one else gets to it. :)

2024-09-11 23:10 UTC, jezdez approved these changes

2024-09-12 10:16 UTC, jaimergp commented on blog/2024-09-12-chatting-with-the-conda-community.mdx
> +slug: "chatting-with-the-conda-community-1"
Sorry one last thing, this should include the date:

```suggestion
slug: "2024-09-12-chatting-with-the-conda-community-1"
```

2024-09-12 10:17 UTC, jaimergp commented on blog/news.json
> +    "slug": "chatting-with-the-conda-community-1",
```suggestion
    "slug": "2024-09-12-chatting-with-the-conda-community-1",
```

2024-09-13 13:44 UTC, merged

2024-09-13 13:44 UTC, jaimergp commented
Thanks!