September 2024 Release blogpost
conda/conda-dot-org pull request #213
Opened 2024-10-01 21:00 UTC by ForgottenProgramme

September Release blogpost

2024-10-01 21:09 UTC, beeankha commented on blog/2024-09-30-september-releases.mdx
> +- Add `conda.core.index.Index` as a faster drop-in replacement of the realized dictionary index. Note: The loggers are no longer implicitly initialized when fetching the index. Instead, you must expl
```suggestion
- Add `conda.core.index.Index` as a faster drop-in replacement of the realized dictionary index. Note: The loggers are no longer implicitly initialized when fetching the index. Instead, you must explicitly call `conda.gateways.logging.initialize_logging`.
```

2024-10-01 21:10 UTC, beeankha commented on blog/2024-09-30-september-releases.mdx
> +conda install -n base conda=24.9.0
```suggestion
conda install -n base conda=24.9.1
```

2024-10-01 21:15 UTC, kenodegard requested changes

2024-10-01 21:15 UTC, kenodegard commented on blog/2024-09-30-september-releases.mdx
> +- Remove deprecated testing entrypoint `shell/bin/conda`. Use `dev/start[.bat]` instead.
```suggestion
- (24.9.1) Remove deprecated testing entrypoint `shell/bin/conda`. Use `dev/start[.bat]` instead.
```

2024-10-01 21:15 UTC, kenodegard commented on blog/2024-09-30-september-releases.mdx
> +- Tweak pending deprecation warning for the upcoming changes in channel defaults.
```suggestion
- (24.9.1) Tweak pending deprecation warning for the upcoming changes in channel defaults.
```

2024-10-01 21:17 UTC, beeankha approved these changes

2024-10-02 15:36 UTC, kenodegard approved these changes

2024-10-02 18:59 UTC, jezdez approved these changes

2024-10-02 19:00 UTC, beeankha approved these changes

2024-10-02 19:02 UTC, kathatherine approved these changes

2024-10-02 19:03 UTC, merged